// ShramLedger Fallback Mock Data for High-Availability Static / Serverless Demonstrations

export const MOCK_WORKERS = [
  {
    id: "worker_ramesh",
    phone: "9876543210",
    name: "Ramesh Kumar (रमेश कुमार)",
    age: 38,
    gender: "Male",
    primary_trade: "Mason / राजमिस्त्री",
    skill_tier: "Highly Skilled",
    state: "Delhi NCR",
    city: "Noida / Greater Noida",
    aadhaar_masked: "XXXX-XXXX-4829",
    eshram_uan_masked: "UAN-9021-4820-1192",
    avatar_url: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop&crop=face",
    joined_date: "2026-01-15",
    dpdp_consent_accepted: true,
    work_entries: [
      {
        id: "WRK-RAM-01",
        worker_id: "worker_ramesh",
        date: "2026-09-12",
        employer_name: "Shree Ram Construction / आर. के. शर्मा",
        employer_phone: "9876543210",
        skill_type: "Mason / राजमिस्त्री",
        skill_category: "skilled",
        location: "Sector 62, Noida, NCR",
        hours_worked: 8.0,
        amount_paid: 850.0,
        payment_mode: "Cash",
        evidence_type: "wage_slip",
        evidence_text: "श्री राम कंस्ट्रक्शन साइट - दैनिक मजदूरी ₹850/-, 8 घंटे, आर. के. शर्मा ठेकेदार",
        confidence_score: 94.0,
        endorsement_status: "verified",
        endorsement_note: "Verified by Contractor R.K. Sharma via Phone OTP.",
        entry_hash: "a4f9c8e102938475bcdef890123456789abcdef0123456789abcdef012345678",
        is_anomaly_flagged: false
      },
      {
        id: "WRK-RAM-02",
        worker_id: "worker_ramesh",
        date: "2026-09-11",
        employer_name: "Gupta Builders & Interiors",
        employer_phone: "9811223344",
        skill_type: "Mason / राजमिस्त्री",
        skill_category: "skilled",
        location: "South Delhi Residential Site",
        hours_worked: 8.5,
        amount_paid: 850.0,
        payment_mode: "UPI",
        evidence_type: "upi_screenshot",
        evidence_text: "UPI Ref 423891029381: ₹850 paid by Gupta Builders (Tile fitting work Day 3)",
        confidence_score: 97.0,
        endorsement_status: "verified",
        endorsement_note: "Digital UPI bank ledger match confirmed.",
        entry_hash: "b5e8d7c601928374abcdef90123456789abcdef0123456789abcdef012345679",
        is_anomaly_flagged: false
      },
      {
        id: "WRK-RAM-03",
        worker_id: "worker_ramesh",
        date: "2026-09-10",
        employer_name: "Gupta Builders & Interiors",
        employer_phone: "9811223344",
        skill_type: "Mason / राजमिस्त्री",
        skill_category: "skilled",
        location: "South Delhi Residential Site",
        hours_worked: 8.0,
        amount_paid: 800.0,
        payment_mode: "UPI",
        evidence_type: "upi_screenshot",
        evidence_text: "UPI Ref 423880192831: ₹800 paid for masonry & plastering work",
        confidence_score: 96.0,
        endorsement_status: "verified",
        endorsement_note: "Digital UPI match verified.",
        entry_hash: "c6d7e8f901827364abcdef890123456789abcdef0123456789abcdef012345680",
        is_anomaly_flagged: false
      },
      {
        id: "WRK-RAM-04",
        worker_id: "worker_ramesh",
        date: "2026-09-08",
        employer_name: "Self-Reported Contractor Log",
        employer_phone: "9899001122",
        skill_type: "Mason / राजमिस्त्री",
        skill_category: "skilled",
        location: "Indirapuram, Ghaziabad",
        hours_worked: 8.0,
        amount_paid: 800.0,
        payment_mode: "Cash",
        evidence_type: "voice_note",
        evidence_text: "Voice note: आज इंदिरापुरम साइट पर 8 घंटे चिनाई का काम किया, 800 रुपए मिले",
        confidence_score: 88.0,
        endorsement_status: "self_attested",
        endorsement_note: "Speech NLP transcription verified with acoustic baseline.",
        entry_hash: "d7e8f9a012938475bcdef90123456789abcdef0123456789abcdef012345681",
        is_anomaly_flagged: false
      }
    ]
  },
  {
    id: "worker_sunita",
    phone: "9845012345",
    name: "Sunita Devi (सुनीता देवी)",
    age: 34,
    gender: "Female",
    primary_trade: "Domestic Cook & Housekeeping",
    skill_tier: "Skilled",
    state: "Karnataka",
    city: "Bengaluru (HSR Layout)",
    aadhaar_masked: "XXXX-XXXX-9182",
    eshram_uan_masked: "UAN-8172-3391-4401",
    avatar_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop&crop=face",
    joined_date: "2026-02-10",
    dpdp_consent_accepted: true,
    work_entries: [
      {
        id: "WRK-SUN-01",
        worker_id: "worker_sunita",
        date: "2026-09-12",
        employer_name: "Mehra Household (HSR Sector 2)",
        employer_phone: "9845112233",
        skill_type: "Cook / रसोइया",
        skill_category: "skilled",
        location: "HSR Layout, Bengaluru",
        hours_worked: 4.0,
        amount_paid: 650.0,
        payment_mode: "UPI",
        evidence_type: "upi_screenshot",
        evidence_text: "UPI txn to Sunita Devi ₹650 from Priyanshu Mehra for culinary catering",
        confidence_score: 99.0,
        endorsement_status: "verified",
        endorsement_note: "Verified by Society Resident Association.",
        entry_hash: "e8f9a0b123456789abcdef0123456789abcdef0123456789abcdef012345682",
        is_anomaly_flagged: false
      },
      {
        id: "WRK-SUN-02",
        worker_id: "worker_sunita",
        date: "2026-09-11",
        employer_name: "Sharma Apartment (Koramangala 4th Block)",
        employer_phone: "9845223344",
        skill_type: "Housekeeping",
        skill_category: "semi_skilled",
        location: "Koramangala, Bengaluru",
        hours_worked: 3.5,
        amount_paid: 550.0,
        payment_mode: "UPI",
        evidence_type: "upi_screenshot",
        evidence_text: "Monthly advance partial installment ₹550",
        confidence_score: 95.0,
        endorsement_status: "verified",
        endorsement_note: "Employer verified on app.",
        entry_hash: "f9a0b1c234567890abcdef0123456789abcdef0123456789abcdef012345683",
        is_anomaly_flagged: false
      }
    ]
  },
  {
    id: "worker_vikram",
    phone: "9820098765",
    name: "Vikram Singh (विक्रम सिंह)",
    age: 29,
    gender: "Male",
    primary_trade: "Electrician / इलेक्ट्रीशियन",
    skill_tier: "Certified Technician",
    state: "Maharashtra",
    city: "Mumbai (Andheri West)",
    aadhaar_masked: "XXXX-XXXX-6351",
    eshram_uan_masked: "UAN-7261-0092-8812",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face",
    joined_date: "2026-03-01",
    dpdp_consent_accepted: true,
    work_entries: [
      {
        id: "WRK-VIK-01",
        worker_id: "worker_vikram",
        date: "2026-09-12",
        employer_name: "Godrej Living Maintenance",
        employer_phone: "9820011223",
        skill_type: "Electrical Wiring",
        skill_category: "highly_skilled",
        location: "Andheri West, Mumbai",
        hours_worked: 8.0,
        amount_paid: 1100.0,
        payment_mode: "Bank Transfer",
        evidence_type: "wage_slip",
        evidence_text: "Job Card #EV-889: Commercial sub-meter installation and circuit inspection",
        confidence_score: 98.0,
        endorsement_status: "verified",
        endorsement_note: "Certified by Site Electrical Engineer.",
        entry_hash: "0a1b2c3d4e5f6789abcdef0123456789abcdef0123456789abcdef012345684",
        is_anomaly_flagged: false
      }
    ]
  }
];

export const MOCK_SCORES = {
  worker_ramesh: {
    overall_score: 785,
    composite_score: 785,
    grade: "A+",
    score_label: "Employment & Income Reliability Score",
    income_stability_score: 88,
    work_continuity_score: 85,
    verified_earnings_score: 92,
    employer_endorsement_score: 90,
    evidence_quality_score: 94,
    skill_demand_score: 87,
    avg_daily_wage: 835.0,
    estimated_monthly_income: 24200.0,
    projected_monthly_income: 24200.0,
    overall_evidence_confidence: 91.0,
    evidence_index: 91.0,
    evidence_breakdown: {
      upi_bank_evidence_pct: 45.0,
      employer_verified_pct: 35.0,
      wage_slips_receipts_pct: 12.0,
      voice_declarations_pct: 8.0,
      overall_evidence_confidence: 91.0,
      strength_band: "Gold (High Fidelity)"
    },
    stability_band: "High Stability (Prime Informal)",
    loan_readiness: "Eligible for up to ₹75,000 Micro-Credit (PMMY Mudra)",
    factors_positive: [
      "88% digital wage trail via UPI and verified bank transfer",
      "100% employer endorsement rate across registered contractors",
      "Zero inter-site shift collisions or biometric anomalies"
    ],
    factors_improvement: [
      "Maintain 90+ consecutive days log for Tier-1 interest discount"
    ],
    credit_tier: "Tier-1 Prime Informal",
    merkle_root: "9e8a7b6c5d4e3f2a109876543210fedcba9876543210abcdef0123456789abcd"
  },
  worker_sunita: {
    overall_score: 742,
    composite_score: 742,
    grade: "A",
    score_label: "Employment & Income Reliability Score",
    income_stability_score: 84,
    work_continuity_score: 80,
    verified_earnings_score: 85,
    employer_endorsement_score: 88,
    evidence_quality_score: 90,
    skill_demand_score: 82,
    avg_daily_wage: 600.0,
    estimated_monthly_income: 18000.0,
    projected_monthly_income: 18000.0,
    overall_evidence_confidence: 88.0,
    evidence_index: 88.0,
    evidence_breakdown: {
      upi_bank_evidence_pct: 70.0,
      employer_verified_pct: 20.0,
      wage_slips_receipts_pct: 5.0,
      voice_declarations_pct: 5.0,
      overall_evidence_confidence: 88.0,
      strength_band: "Gold (High Fidelity)"
    },
    stability_band: "Moderate Stability (Near Prime)",
    loan_readiness: "Eligible for up to ₹50,000 Micro-Credit (PM SVANidhi)",
    factors_positive: [
      "High UPI digital transaction density (>90%)",
      "Multiple verified household employers"
    ],
    factors_improvement: [
      "Log consecutive days across months to raise score to Grade A+"
    ],
    credit_tier: "Tier-1 Prime Informal",
    merkle_root: "8f7e6d5c4b3a201987654321fedcba9876543210abcdef0123456789abcde0"
  },
  worker_vikram: {
    overall_score: 820,
    composite_score: 820,
    grade: "A+",
    score_label: "Employment & Income Reliability Score",
    income_stability_score: 94,
    work_continuity_score: 90,
    verified_earnings_score: 95,
    employer_endorsement_score: 92,
    evidence_quality_score: 96,
    skill_demand_score: 93,
    avg_daily_wage: 1100.0,
    estimated_monthly_income: 33000.0,
    projected_monthly_income: 33000.0,
    overall_evidence_confidence: 95.0,
    evidence_index: 95.0,
    evidence_breakdown: {
      upi_bank_evidence_pct: 60.0,
      employer_verified_pct: 30.0,
      wage_slips_receipts_pct: 10.0,
      voice_declarations_pct: 0.0,
      overall_evidence_confidence: 95.0,
      strength_band: "Platinum (Cryptographically Bound)"
    },
    stability_band: "High Stability (Prime Informal)",
    loan_readiness: "Eligible for up to ₹1,50,000 Collateral-Free Credit",
    factors_positive: [
      "Consistent high daily wage (₹1,100/day)",
      "Certified electrical technician credential verified"
    ],
    factors_improvement: [
      "Enroll apprentice workers under PM Vishwakarma"
    ],
    credit_tier: "Tier-1 Prime Informal",
    merkle_root: "7e6d5c4b3a201987654321fedcba9876543210abcdef0123456789abcde01f"
  }
};

export const MOCK_SCHEMES = {
  worker_ramesh: [
    {
      id: "SCHEME-PMSYM-01",
      scheme_id: "PMSYM",
      name: "Pradhan Mantri Shram Yogi Maan-dhan (PM-SYM)",
      name_hi: "प्रधानमंत्री श्रम योगी मान-धन (PM-SYM)",
      ministry: "Ministry of Labour & Employment, Govt. of India",
      category: "Pension",
      benefit_amount: "₹3,000/Month Guaranteed Pension",
      benefit_summary: "₹3,000/month guaranteed pension after age 60 with 50% central match",
      description: "Voluntary and contributory pension scheme for informal workers with entry age between 18 to 40 years, with 50% central government matching contribution.",
      description_hi: "असंगठित श्रमिकों के लिए मासिक ₹3,000 की सुनिश्चित पेंशन योजना, जिसमें 50% अंशदान केंद्र सरकार द्वारा दिया जाता है।",
      eligibility_status: "Eligible (Auto-Verified against ShramLedger)",
      conditions_met: ["Age between 18-40", "Monthly verified income under ₹15,000 threshold", "e-Shram registered"],
      pending_conditions: [],
      eligibility_match: true,
      match_score: 96,
      match_confidence: 96.0,
      action_url: "https://maandhan.in/",
      required_documents: ["Aadhaar Card", "Savings Bank Account / Jan Dhan", "e-Shram UAN"]
    },
    {
      id: "SCHEME-PMSBY-02",
      scheme_id: "PMSBY",
      name: "Pradhan Mantri Suraksha Bima Yojana (PMSBY)",
      name_hi: "प्रधानमंत्री सुरक्षा बीमा योजना (PMSBY)",
      ministry: "Ministry of Finance, Govt. of India",
      category: "Social Security",
      benefit_amount: "₹2,00,000 Accidental Death Cover",
      benefit_summary: "₹2,00,000 accidental death/disability insurance at ₹20/year premium",
      description: "Annual accident insurance cover of ₹2 lakh for death or permanent total disability, and ₹1 lakh for permanent partial disability at just ₹20 per year.",
      description_hi: "मात्र ₹20 प्रति वर्ष पर ₹2 लाख का दुर्घटना बीमा कवर (मृत्यु अथवा पूर्ण दिव्यांगता पर)।",
      eligibility_status: "Eligible (Active Linkage)",
      conditions_met: ["Active Savings Bank Account", "Age between 18-70"],
      pending_conditions: [],
      eligibility_match: true,
      match_score: 99,
      match_confidence: 99.0,
      action_url: "https://www.jansuraksha.gov.in/",
      required_documents: ["Aadhaar Linked Bank Account"]
    },
    {
      id: "SCHEME-BOCW-03",
      scheme_id: "BOCW_WELFARE",
      name: "BOCW Statutory Welfare Board Safety & Tool Grant",
      name_hi: "भवन एवं अन्य निर्माण कर्मकार (BOCW) टूलकिट एवं कल्याण अनुदान",
      ministry: "Delhi / State BOCW Welfare Board",
      category: "Social Security",
      benefit_amount: "₹15,000 Modern Tool Grant + Family Welfare",
      benefit_summary: "Toolbox subsidy of ₹15,000, daughter marriage grant ₹51,000 & accident cover",
      description: "Direct statutory benefits for construction workers completing 90+ verified mandays per year, including tools allowance, health assistance, and life cover.",
      description_hi: "निर्माण श्रमिकों के लिए आधुनिक औजार सब्सिडी (₹15,000), स्वास्थ्य सहायता एवं पारिवारिक कल्याण अनुदान।",
      eligibility_status: "Eligible (>90 days verified construction muster on record)",
      conditions_met: ["90+ Days Verified Construction Record", "Employer Endorsement on ShramLedger", "Aadhaar Linked"],
      pending_conditions: [],
      eligibility_match: true,
      match_score: 98,
      match_confidence: 98.0,
      action_url: "https://bocw.delhi.gov.in/",
      required_documents: ["BOCW Card / Application", "Employer Attestation Certificate", "Bank Passbook"]
    },
    {
      id: "SCHEME-MUDRA-04",
      scheme_id: "PMMY_MUDRA",
      name: "Pradhan Mantri Mudra Yojana (Shishu Tier)",
      name_hi: "प्रधानमंत्री मुद्रा योजना (शिशु ऋण)",
      ministry: "Department of Financial Services, Govt. of India",
      category: "Credit",
      benefit_amount: "Up to ₹50,000 Collateral-Free Micro-Loan",
      benefit_summary: "Collateral-free institutional micro-credit at subsidized interest rates",
      description: "Micro-credit for informal micro-enterprises, tools purchase, and working capital with zero collateral requirements.",
      description_hi: "कारीगरों और अनौपचारिक कामगारों के लिए बिना किसी गारंटी के ₹50,000 तक का आसान संस्थागत ऋण।",
      eligibility_status: "Pre-Qualified (ShramScore 785 Grade A+)",
      conditions_met: ["ShramScore > 650", "Verified Income History", "DPDP Digital Audit Proof"],
      pending_conditions: [],
      eligibility_match: true,
      match_score: 94,
      match_confidence: 94.0,
      action_url: "https://www.mudra.org.in/",
      required_documents: ["ShramLedger Sanction Letter", "Aadhaar Card", "Bank Account Statement"]
    },
    {
      id: "SCHEME-PMJAY-05",
      scheme_id: "PMJAY",
      name: "Ayushman Bharat PM-JAY Cashless Health Cover",
      name_hi: "आयुष्मान भारत प्रधानमंत्री जन आरोग्य योजना",
      ministry: "National Health Authority",
      category: "Health",
      benefit_amount: "₹5,00,000/Year Cashless Hospitalization",
      benefit_summary: "Cashless secondary and tertiary hospitalization cover across empaneled hospitals",
      description: "Comprehensive hospitalization cover for low-income informal earners and their families with cashless treatment across 27,000+ hospitals.",
      description_hi: "प्रति परिवार प्रति वर्ष ₹5,00,000 तक का कैशलेस इलाज देशभर के सूचीबद्ध सरकारी व निजी अस्पतालों में।",
      eligibility_status: "Eligible (SECC / BOCW Verified)",
      conditions_met: ["SECC / BOCW Beneficiary Register Linkage", "Aadhaar Verified"],
      pending_conditions: [],
      eligibility_match: true,
      match_score: 92,
      match_confidence: 92.0,
      action_url: "https://pmjay.gov.in/",
      required_documents: ["Ration Card / BOCW Certificate", "Aadhaar Card"]
    }
  ]
};

export const MOCK_CERTIFICATES = {
  worker_ramesh: {
    certificate_id: "CERT-SL-2026-RAMESH-8921",
    worker_id: "worker_ramesh",
    worker_name: "Ramesh Kumar (रमेश कुमार)",
    primary_trade: "Mason / राजमिस्त्री",
    trade: "Mason / राजमिस्त्री",
    location: "Noida Sector 62, Delhi NCR",
    issue_date: "12 September 2026",
    issued_date: "12 September 2026",
    verified_period: "15 Jan 2026 – 12 Sep 2026",
    total_work_days: 42,
    total_entries_attested: 42,
    total_earnings: 34850.0,
    average_monthly_wage: 24200.0,
    shram_score: 785,
    composite_shram_score: 785,
    evidence_strength: 91.0,
    verified_entries_ratio: "100%",
    merkle_root: "9e8a7b6c5d4e3f2a109876543210fedcba9876543210abcdef0123456789abcd",
    digital_signature: "SIG-ECDSA-SHA256-4b8c9a1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b",
    is_valid: true,
    tamper_detected: false,
    verification_url: "https://frontend-eureka-b5b5.vercel.app/verify/CERT-SL-2026-RAMESH-8921",
    qr_payload: "https://frontend-eureka-b5b5.vercel.app/verify/CERT-SL-2026-RAMESH-8921",
    issuer: "ShramLedger Autonomous Proof Authority (Bharat Decentralized Node 01)",
    entries_count: 4
  },
  worker_sunita: {
    certificate_id: "CERT-SL-2026-SUNITA-4401",
    worker_id: "worker_sunita",
    worker_name: "Sunita Devi (सुनीता देवी)",
    primary_trade: "Domestic Cook & Housekeeping",
    trade: "Domestic Cook & Housekeeping",
    location: "HSR Layout, Bengaluru, Karnataka",
    issue_date: "12 September 2026",
    issued_date: "12 September 2026",
    verified_period: "10 Feb 2026 – 12 Sep 2026",
    total_work_days: 35,
    total_entries_attested: 35,
    total_earnings: 21500.0,
    average_monthly_wage: 18000.0,
    shram_score: 742,
    composite_shram_score: 742,
    evidence_strength: 88.0,
    verified_entries_ratio: "98%",
    merkle_root: "8f7e6d5c4b3a201987654321fedcba9876543210abcdef0123456789abcde0",
    digital_signature: "SIG-ECDSA-SHA256-1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b",
    is_valid: true,
    tamper_detected: false,
    verification_url: "https://frontend-eureka-b5b5.vercel.app/verify/CERT-SL-2026-SUNITA-4401",
    qr_payload: "https://frontend-eureka-b5b5.vercel.app/verify/CERT-SL-2026-SUNITA-4401",
    issuer: "ShramLedger Autonomous Proof Authority (Bharat Decentralized Node 01)",
    entries_count: 2
  },
  worker_vikram: {
    certificate_id: "CERT-SL-2026-VIKRAM-8812",
    worker_id: "worker_vikram",
    worker_name: "Vikram Singh (विक्रम सिंह)",
    primary_trade: "Electrician / इलेक्ट्रीशियन",
    trade: "Electrician / इलेक्ट्रीशियन",
    location: "Andheri West, Mumbai, Maharashtra",
    issue_date: "12 September 2026",
    issued_date: "12 September 2026",
    verified_period: "01 Mar 2026 – 12 Sep 2026",
    total_work_days: 50,
    total_entries_attested: 50,
    total_earnings: 55000.0,
    average_monthly_wage: 33000.0,
    shram_score: 820,
    composite_shram_score: 820,
    evidence_strength: 95.0,
    verified_entries_ratio: "100%",
    merkle_root: "7e6d5c4b3a201987654321fedcba9876543210abcdef0123456789abcde01f",
    digital_signature: "SIG-ECDSA-SHA256-9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a109876543210fedcba9876543210",
    is_valid: true,
    tamper_detected: false,
    verification_url: "https://frontend-eureka-b5b5.vercel.app/verify/CERT-SL-2026-VIKRAM-8812",
    qr_payload: "https://frontend-eureka-b5b5.vercel.app/verify/CERT-SL-2026-VIKRAM-8812",
    issuer: "ShramLedger Autonomous Proof Authority (Bharat Decentralized Node 01)",
    entries_count: 1
  }
};

export const MOCK_EMPLOYER_PENDING = [
  {
    entry_id: "WRK-RAM-04",
    worker_id: "worker_ramesh",
    worker_name: "Ramesh Kumar (रमेश कुमार)",
    worker_phone: "+91 98765 43210",
    worker_avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    skill_type: "Mason / राजमिस्त्री",
    trade: "Mason / राजमिस्त्री",
    date: "2026-09-08",
    work_date: "2026-09-08",
    hours_worked: 8.0,
    amount_paid: 850.0,
    amount_claimed: 850.0,
    payment_mode: "Cash",
    location: "Indirapuram Sector 4 Site, Ghaziabad",
    claimed_site: "Indirapuram Sector 4 Site, Ghaziabad",
    evidence_type: "voice_log",
    evidence_text: "8 घंटे चिनाई का काम पूरा किया, ₹850 दिहाड़ी तय हुई थी।",
    confidence_score: 92.5,
    current_status: "pending",
    verification_due_days: 2
  },
  {
    entry_id: "WRK-SUN-02",
    worker_id: "worker_sunita",
    worker_name: "Sunita Devi (सुनीता देवी)",
    worker_phone: "+91 98201 23456",
    worker_avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    skill_type: "Helper / सहायक",
    trade: "Helper / सहायक",
    date: "2026-09-11",
    work_date: "2026-09-11",
    hours_worked: 8.0,
    amount_paid: 700.0,
    amount_claimed: 700.0,
    payment_mode: "UPI",
    location: "Noida Sector 62 Infrastructure Extension Site",
    claimed_site: "Noida Sector 62 Infrastructure Extension Site",
    evidence_type: "ocr_wage_slip",
    evidence_text: "साइट मस्टर रोल पर्ची संख्या #402 - सहायक कार्य।",
    confidence_score: 94.0,
    current_status: "pending",
    verification_due_days: 1
  }
];

export const MOCK_FRAUD_ALERTS = [
  {
    alert_id: "ALT-2026-8812",
    id: "ALT-2026-8812",
    worker_id: "worker_kailash",
    worker_name: "Kailash Chand (कैलाश चंद)",
    alert_type: "SHIFT_COLLISION",
    type: "SHIFT_COLLISION",
    severity: "HIGH",
    description: "Concurrent biometric shift logged at Noida Sec 62 and Gurgaon CyberCity within 20 mins.",
    detected_at: "12 Sep 2026, 11:20 UTC",
    timestamp: "12 Sep 2026, 11:20 UTC",
    status: "PENDING_REVIEW",
    evidence_snapshot: {
      site_a: "L&T Metro Pier 14 (Noida Sec 62)",
      site_b: "DLF CyberCity Phase 3 (Gurgaon)",
      time_delta: "20 minutes",
      geographical_distance: "42.5 km across NCR",
      collision_probability: "99.8% Concurrent Ghost Billing"
    }
  },
  {
    alert_id: "ALT-2026-9921",
    id: "ALT-2026-9921",
    worker_id: "worker_ramesh",
    worker_name: "Ramesh Kumar (रमेश कुमार)",
    alert_type: "WAGE_SPIKE_OUTLIER",
    type: "WAGE_SPIKE_OUTLIER",
    severity: "MEDIUM",
    description: "Daily wage ₹1,800 claimed on 02 Sep exceeds NCR masonry P95 benchmark (₹950).",
    detected_at: "11 Sep 2026, 16:40 UTC",
    timestamp: "11 Sep 2026, 16:40 UTC",
    status: "PENDING_REVIEW",
    evidence_snapshot: {
      claimed_wage: "₹1,800.00 / 8 hrs",
      regional_p95_limit: "₹950.00",
      variance: "+89.4% above median skilled rate",
      investigator_note: "Review contractor invoice for specialized decorative stone masonry"
    }
  }
];

export const MOCK_AUDIT_LOGS = [
  {
    id: "AUD-20260913-9A1B2C",
    timestamp: "13 Sep 2026, 14:15:20 UTC",
    actor_id: "LEDGER-CONSENSUS-NODE-01",
    actor_role: "Validator",
    action: "MERKLE_ROOT_ANCHORED",
    resource_type: "LedgerBlock",
    resource_id: "BLK-10482",
    details: { entries_count: 12, algorithm: "SHA-256 Merkle DAG" },
    ledger_hash: "9e8a7b6c5d4e3f2a109876543210fedcba9876543210abcdef0123456789abcd"
  },
  {
    id: "AUD-20260913-8B2A3D",
    timestamp: "13 Sep 2026, 13:45:00 UTC",
    actor_id: "WORKER-RAMESH-KUMAR",
    actor_role: "Worker",
    action: "DPDP_CONSENT_GRANTED",
    resource_type: "ConsentRecord",
    resource_id: "CR-8812",
    details: { purpose: "LOAN_UNDERWRITING_MUDRA", requester: "HDFC Rural Bank", valid_days: 90 },
    ledger_hash: "3a9c72e91b58091cf8e84a7e91240c1a93821098471239084129841209384120"
  },
  {
    id: "AUD-20260913-7C3D4E",
    timestamp: "13 Sep 2026, 12:10:15 UTC",
    actor_id: "CONTRACTOR-LNT-04",
    actor_role: "Employer",
    action: "BULK_MUSTER_INGESTION",
    resource_type: "MusterBatch",
    resource_id: "MST-2026-0913",
    details: { workers_count: 120, total_payout: 98400.0, site: "Mukundpur Metro Depot" },
    ledger_hash: "7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b"
  },
  {
    id: "AUD-20260913-6D4E5F",
    timestamp: "13 Sep 2026, 10:30:42 UTC",
    actor_id: "BANK-FINTECH-API",
    actor_role: "Lender",
    action: "QUERY_LENDER_SUMMARY",
    resource_type: "WorkerProfile",
    resource_id: "worker_ramesh",
    details: { verified_monthly_income: 24200.0, shram_score: 785 },
    ledger_hash: "8f4a1c3d9e2b7a0f6e5d4c3b2a10987654321fedcba9876543210abcdef01234"
  },
  {
    id: "AUD-20260913-5E5F6A",
    timestamp: "13 Sep 2026, 09:12:08 UTC",
    actor_id: "STATE-MISSION-DIRECTOR",
    actor_role: "Admin",
    action: "DISPATCH_DBT_WELFARE",
    resource_type: "BenefitPackage",
    resource_id: "DBT-UP-2026-8A1C",
    details: { scheme: "PM Vishwakarma Toolkit (₹15,000)", recipient: "Ramesh Kumar" },
    ledger_hash: "3f8b9a1c4d2e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a"
  }
];

export const MOCK_API_KEYS = [
  {
    key_id: "key_live_nbfc_01",
    name: "HDFC Rural Micro-Finance Production API",
    key_prefix: "shram_live_hdfc_8a92f4c1e0",
    environment: "production",
    created_at: "15 Aug 2026, 10:00 UTC",
    last_used_at: "13 Sep 2026, 14:20 UTC",
    is_active: true,
    rate_limit_rpm: 600
  },
  {
    key_id: "key_sandbox_01",
    name: "L&T Construction Site Integration Sandbox",
    key_prefix: "shram_sand_lnt_4f3b1900d8",
    environment: "sandbox",
    created_at: "20 Aug 2026, 11:30 UTC",
    last_used_at: "13 Sep 2026, 09:15 UTC",
    is_active: true,
    rate_limit_rpm: 120
  }
];

export const MOCK_WELFARE_ANALYTICS = {
  total_workers_enrolled: 4821,
  total_workers_indexed: "4,821,940",
  total_work_records_logged: 18450,
  active_daily_attestations: "842,190",
  total_verified_payouts_inr: 15280000.0,
  total_wages_verified: "₹184.2 Cr",
  average_daily_wage_inr: 825.0,
  overall_verification_rate: 94.6,
  avg_shram_score: 762,
  bank_credit_linked_rate: "34.8%",
  bocw_cess_compliance_pct: "91.4%",
  scheme_matching_rate: "88.2% of enrolled informal workers qualify for at least one Central/State welfare scheme or Mudra micro-credit",
  occupation_distribution: [
    { trade: "Mason / राजमिस्त्री", workers_count: 1820, percentage: 37.8 },
    { trade: "Helper / सहायक", workers_count: 1240, percentage: 25.7 },
    { trade: "Carpenter / बढ़ई", workers_count: 890, percentage: 18.5 },
    { trade: "Electrician / इलेक्ट्रीशियन", workers_count: 520, percentage: 10.8 },
    { trade: "Plumber / प्लंबर", workers_count: 351, percentage: 7.2 }
  ],
  state_distribution: [
    { state: "Delhi / NCR", workers: 2140, avg_wage: 845.0 },
    { state: "Uttar Pradesh", workers: 1680, avg_wage: 780.0 },
    { state: "Maharashtra", workers: 1001, avg_wage: 810.0 }
  ],
  top_trades: [
    { trade: "Masonry & Civil Construction", count: "42%" },
    { trade: "Domestic Care & Cooking", count: "26%" },
    { trade: "Electrical & Plumbing", count: "18%" },
    { trade: "Transport & Logistics", count: "14%" }
  ]
};
